name: "Test Raku"
on:
  push:
    paths:
      - "**.rakumod"
      - "META6.json"
      - ".github/workflows/test.yaml"
  pull_request:
    paths:
      - "**.rakumod"
      - "META6.json"
      - ".github/workflows/test.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jjmerelo/raku-test:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name : Install kazmath
        run: ./download-and-compile-kazmath-alpine.sh
      - name: Install pre-requisites and test
        run: zef install --deps-only . && zef --debug test .


